/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import vista.Mecanicos;
import vista.Facturas;
import vista.Clientes;

/**
 *
 * @author Administrador
 */
public class Menú extends javax.swing.JFrame {

    /**
     * Creates new form Menú
     */
    public Menú() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonVehiculo = new javax.swing.JButton();
        jButtonCliente = new javax.swing.JButton();
        jButtonMecanico = new javax.swing.JButton();
        jButtonServicio = new javax.swing.JButton();
        jButtonTurno = new javax.swing.JButton();
        jButtonFactura = new javax.swing.JButton();
        jButtonRepuesto = new javax.swing.JButton();
        jButtonTaller = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ménu Taller");

        jButtonVehiculo.setBackground(new java.awt.Color(0, 102, 102));
        jButtonVehiculo.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVehiculo.setText("Vehículos");
        jButtonVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVehiculoActionPerformed(evt);
            }
        });

        jButtonCliente.setBackground(new java.awt.Color(0, 102, 102));
        jButtonCliente.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonCliente.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCliente.setText("Clientes");
        jButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClienteActionPerformed(evt);
            }
        });

        jButtonMecanico.setBackground(new java.awt.Color(0, 102, 102));
        jButtonMecanico.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonMecanico.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMecanico.setText("Mécanicos");
        jButtonMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMecanicoActionPerformed(evt);
            }
        });

        jButtonServicio.setBackground(new java.awt.Color(0, 102, 102));
        jButtonServicio.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonServicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonServicio.setText("Servicios");
        jButtonServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonServicioActionPerformed(evt);
            }
        });

        jButtonTurno.setBackground(new java.awt.Color(0, 102, 102));
        jButtonTurno.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonTurno.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTurno.setText("Turnos");
        jButtonTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTurnoActionPerformed(evt);
            }
        });

        jButtonFactura.setBackground(new java.awt.Color(0, 102, 102));
        jButtonFactura.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonFactura.setForeground(new java.awt.Color(255, 255, 255));
        jButtonFactura.setText("Facturas");
        jButtonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFacturaActionPerformed(evt);
            }
        });

        jButtonRepuesto.setBackground(new java.awt.Color(0, 102, 102));
        jButtonRepuesto.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonRepuesto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRepuesto.setText("Repuestos");
        jButtonRepuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepuestoActionPerformed(evt);
            }
        });

        jButtonTaller.setBackground(new java.awt.Color(0, 102, 102));
        jButtonTaller.setFont(new java.awt.Font("Sitka Display", 3, 18)); // NOI18N
        jButtonTaller.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTaller.setText("Taller");
        jButtonTaller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTallerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTaller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonVehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(jButtonTurno, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButtonServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jButtonRepuesto)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonVehiculo)
                            .addComponent(jButtonCliente))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonMecanico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTaller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRepuesto)
                    .addComponent(jButtonFactura))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClienteActionPerformed
      Clientes cliente = new Clientes();
      cliente.setLocationRelativeTo(null);
      cliente.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButtonClienteActionPerformed

    private void jButtonVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVehiculoActionPerformed
     Vehiculos vehiculo = new Vehiculos ();
     vehiculo.setLocationRelativeTo(null);
     vehiculo.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButtonVehiculoActionPerformed

    private void jButtonRepuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepuestoActionPerformed
       Respuestos repuesto = new Respuestos ();
       repuesto.setLocationRelativeTo(null);
       repuesto.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonRepuestoActionPerformed

    private void jButtonMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMecanicoActionPerformed
     Mecanicos mecanico = new Mecanicos ();
     mecanico.setLocationRelativeTo(null);
     mecanico.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButtonMecanicoActionPerformed

    private void jButtonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFacturaActionPerformed
       Facturas factura = new Facturas ();
       factura.setLocationRelativeTo(null);
       factura.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonFacturaActionPerformed

    private void jButtonTallerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTallerActionPerformed
       Taller taller = new Taller ();
       taller.setLocationRelativeTo(null);
       taller.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jButtonTallerActionPerformed

    private void jButtonServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonServicioActionPerformed
     Servicios servicio = new Servicios ();
     servicio.setLocationRelativeTo(null);
     servicio.setVisible(true);
     this.dispose();
    }//GEN-LAST:event_jButtonServicioActionPerformed

    private void jButtonTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTurnoActionPerformed
      Turnos turno = new Turnos ();
      turno.setLocationRelativeTo(null);
      turno.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_jButtonTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menú.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menú().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCliente;
    private javax.swing.JButton jButtonFactura;
    private javax.swing.JButton jButtonMecanico;
    private javax.swing.JButton jButtonRepuesto;
    private javax.swing.JButton jButtonServicio;
    private javax.swing.JButton jButtonTaller;
    private javax.swing.JButton jButtonTurno;
    private javax.swing.JButton jButtonVehiculo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
